# Lists all recipes
list:
    @just --list

# Builds the fake-ipl binary, copies it to the resources folder and converts it to a .dol
build:
    @echo -e "=> Building fake-ipl.elf ..."
    @cargo build --release
    @echo -e "=> Copying fake-ipl.elf to local resources folder ..."
    @cp ../target/powerpc-nintendo-gamecube-eabi/release/fake-ipl.elf ../local/fake-ipl.elf
    @echo -e "=> Converting fake-ipl.elf to fake-ipl.dol ..."
    @cd .. && cargo run -q -p cubetool convert -i local/fake-ipl.elf -o local/fake-ipl.dol
    @echo -e "=> Done!"
    @cd .. && cargo run -q -p cubetool inspect -i local/fake-ipl.dol
