[package]
name = "dolinfo"
version = "0.1.0"
edition = "2024"

[dependencies]
dolfile = { path = "../dolfile" }
eyre-pretty = { path = "/home/vxpm/dev/eyre-pretty" }

bytesize = "2"
clap = { version = "4.5", features = ["derive"] }
comfy-table = "7.1"
