import package::tev::Input;

const R3C: Input = 0x0;
const R3A: Input = 0x1;
const R0C: Input = 0x2;
const R0A: Input = 0x3;
const R1C: Input = 0x4;
const R1A: Input = 0x5;
const R2C: Input = 0x6;
const R2A: Input = 0x7;
const TEX_COLOR: Input = 0x8;
const TEX_ALPHA: Input = 0x9;
const RAS_COLOR: Input = 0xA;
const RAS_ALPHA: Input = 0xB;
const ONE: Input = 0xC;
const HALF: Input = 0xD;
const CONSTANT: Input = 0xE;
const ZERO: Input = 0xF;