[package]
name = "cli"
version = "0.1.0"
edition = "2024"

[dependencies]
eyre-pretty = { path = "/home/vxpm/dev/eyre-pretty" }
hemisphere = { path = "../hemisphere" }

tracing.workspace = true
tracing-subscriber.workspace = true
binrw.workspace = true

gdbstub = "0.7"
tracing-appender = "0.2"
