[package]
name = "iso"
description = "A GameCube .iso file parser"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
easyerr.workspace = true
binrw.workspace = true
dol = { path = "../dol" }
