[package]
name = "cubefile"
description = "A CLI to inspect files related to the GameCube"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
dol = { path = "../dol" }
iso = { path = "../iso" }
bytesize.workspace = true
clap.workspace = true
eyre-pretty.workspace = true
binrw.workspace = true

comfy-table = { version = "7.1", default-features = false }
petgraph = "0.8"
